// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Trening_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("TreningApp.Models.Cwiczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaPowtorzen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaSerii")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaCwiczenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrzerwaMiedzySeriami")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("TreningApp.Models.HistoriaTreningu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CzasTrwania")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataTreningu")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPlanu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaPlanu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoriaTreningow");
                });

            modelBuilder.Entity("TreningApp.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscObwodow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Poziom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrzerwaMiedzyObwodami")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plany");
                });

            modelBuilder.Entity("TreningApp.Models.Cwiczenie", b =>
                {
                    b.HasOne("TreningApp.Models.Plan", null)
                        .WithMany("Cwiczenia")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreningApp.Models.Plan", b =>
                {
                    b.Navigation("Cwiczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
