// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingApp.Api.Data;

#nullable disable

namespace TrainingApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428074644_AddPasswordHashToUser")]
    partial class AddPasswordHashToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("TrainingApp.Api.Models.Cwiczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaPowtorzen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaSerii")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaCwiczenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrzerwaMiedzySeriami")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.HistoriaTreningu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CzasTrwania")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataTreningu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazwaPlanu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("HistoriaTreningow");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscObwodow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Poziom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrzerwaMiedzyObwodami")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plany");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.Cwiczenie", b =>
                {
                    b.HasOne("TrainingApp.Api.Models.Plan", "Plan")
                        .WithMany("Cwiczenia")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.HistoriaTreningu", b =>
                {
                    b.HasOne("TrainingApp.Api.Models.Plan", "Plan")
                        .WithMany("HistoriaTreningow")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.Plan", b =>
                {
                    b.HasOne("TrainingApp.Api.Models.User", "User")
                        .WithMany("Plany")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.Plan", b =>
                {
                    b.Navigation("Cwiczenia");

                    b.Navigation("HistoriaTreningow");
                });

            modelBuilder.Entity("TrainingApp.Api.Models.User", b =>
                {
                    b.Navigation("Plany");
                });
#pragma warning restore 612, 618
        }
    }
}
